### ISSUE TITLE
Enable NPM/Bower Explicitly Doesnt work. 

### ISSUE THREAD

**Issue by callerc1** [nullivex/grunt-project-update#2]
When setting this:
`projectUpdate: {
  update: {
    npm: false,
    bower: true
  }
}`

npm update commands still run on `grunt`.

if manager file exists then this takes precedence over the flag.

**Comment by nullivex** [comment]
Okay,

Ill see if I can get this fixed and a new version rolled out.

Weird github didnt show me this update in email. Sorry for missing it.
